# Generated by Django 4.2.7 on 2026-01-02 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="AI provider name (e.g., 'openai', 'anthropic', 'google')", max_length=100)),
                ('encrypted_api_key', models.TextField(help_text='Encrypted API key for the provider')),
                ('model', models.CharField(help_text="Default AI model name (e.g., 'gpt-4', 'claude-3-opus')", max_length=100)),
                ('base_url', models.URLField(blank=True, help_text='Custom API endpoint URL (optional, for self-hosted models)', max_length=500, null=True)),
                ('name', models.CharField(blank=True, help_text='User-friendly label/name for this integration', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this integration is currently active/enabled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this integration was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this integration was last updated')),
                ('user', models.ForeignKey(help_text='The user who owns this AI integration', on_delete=django.db.models.deletion.CASCADE, related_name='ai_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_integration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='ai_integrat_user_id_d0ad4c_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
