# Generated by Django 4.2.7 on 2025-12-31 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'ingredient',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prepTime', models.IntegerField()),
                ('cookTime', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('imageUrl', models.URLField(max_length=500)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipe',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('instructions', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'step',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.step')),
            ],
            options={
                'db_table': 'step_ingredient',
                'unique_together': {('step', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='step',
            name='ingredients',
            field=models.ManyToManyField(related_name='steps', through='recipe.StepIngredient', to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.tag')),
            ],
            options={
                'db_table': 'recipe_tag',
                'unique_together': {('recipe', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='recipe.RecipeTag', to='recipe.tag'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe'),
        ),
    ]
