# Generated by Django 4.2.7 on 2025-12-31 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        # SQLite cannot alter primary key types, so we need to recreate tables
        # This will result in data loss, but is necessary for the schema change
        
        # Drop all tables that depend on Recipe, Ingredient, and Step
        migrations.DeleteModel('StepIngredient'),
        migrations.DeleteModel('RecipeTag'),
        migrations.DeleteModel('Step'),
        migrations.DeleteModel('Ingredient'),
        migrations.DeleteModel('Recipe'),
        
        # Recreate Recipe with auto-incrementing ID
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prepTime', models.IntegerField()),
                ('cookTime', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('imageUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipe',
                'ordering': ['-createdAt'],
            },
        ),
        
        # Recreate Ingredient with auto-incrementing ID
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe')),
            ],
            options={
                'db_table': 'ingredient',
                'ordering': ['id'],
            },
        ),
        
        # Recreate Step with auto-incrementing ID
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('order', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.recipe')),
            ],
            options={
                'db_table': 'step',
                'ordering': ['order', 'id'],
            },
        ),
        
        # Recreate StepIngredient
        migrations.CreateModel(
            name='StepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.step')),
            ],
            options={
                'db_table': 'step_ingredient',
                'unique_together': {('step', 'ingredient')},
            },
        ),
        
        # Recreate RecipeTag (Tag model should still exist from 0001)
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.tag')),
            ],
            options={
                'db_table': 'recipe_tag',
                'unique_together': {('recipe', 'tag')},
            },
        ),
        
        # Add many-to-many relationships
        migrations.AddField(
            model_name='step',
            name='ingredients',
            field=models.ManyToManyField(related_name='steps', through='recipe.StepIngredient', to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='recipe.RecipeTag', to='recipe.tag'),
        ),
    ]
